### PR TITLE
Had added train status

### PR DESCRIPTION
**Pull request by EvangelinPakyaFlora**
Hi sir iam glora kindly review and accept my changes

### CODE REVIEW

**Comment by EvanaKeziah** [comment]
I have tried to add new features sir

**Comment by VasanthiLingappan** [comment]
I have added few new features sir. Please pull the request.

**Comment by SelladuraiB** [comment]
Dear Arul sir

**Comment by Dharshinipriya-2810** [comment]
Dear Arul Sir, 
                     Kindly merge Statue feature

**Pull request merged**
